name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - TechStudent10
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: X happened but I expected Y to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Proton are you running?
    validations:
      required: true
  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate Issues
      description: By submitting this issue, you agree that you have searched the Issues tab and have found no issues relating to your problem OR the solutions provided don't work for you.
      options:
        - label: There are no duplicate issues/the solutions provided don't work for me.
          required: true